# Generated by Django 2.2.14 on 2021-10-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_add_creation_and_modification_dates_to_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='storage_bytes',
            field=models.IntegerField(default=0),
        ),
    ]
