# Generated by Django 2.2.14 on 2021-10-25 18:57

from django.conf import settings
from django.db import migrations
from django.db.models import Count


def delete_empty():
    pass

def remove_duplicates(apps, schema_editor):
        SubmissionCounter = apps.get_model("logger", "SubmissionCounter")
        db_alias = schema_editor.connection.alias
        queryset = SubmissionCounter.objects.using(db_alias).values('timestamp', 'user').annotate(pk_count=Count('pk')).filter(pk_count__gt=1)
        to_delete = []
        for counter in queryset:
            to_delete.extend(SubmissionCounter.objects.filter(
                timestamp=counter['timestamp'], user=counter['user']).values_list('pk', flat=True)[1:]
            )

        SubmissionCounter.objects.filter(pk__in=to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logger', '0020_submission_counter_timestamp_as_date'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
        migrations.AlterUniqueTogether(
            name='submissioncounter',
            unique_together={('user', 'timestamp')},
        ),
    ]
